name: Microservice1 .Net
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore src/services/Microservice1/Microservice.Api/Microservice.Api.csproj
    - name: Build
      run: dotnet build -c Release --no-restore src/services/Microservice1/Microservice.Api/Microservice.Api.csproj
    - name: Test
      run: dotnet test src/services/Microservice1/Microservice.Core.Tests/Microservice.Core.Tests.csproj
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Build
      uses: docker/build-push-action@v2
      with:
        context: src/services/Microservice1
        tags: Microservice1:latest
        push: false
